#!/bin/zsh
# package-macos.sh — build a distributable, self-contained "Blocks for
# Developers.app" for macOS (Apple Silicon) and zip it for distribution.
#
# What it does, end to end:
#   1. Build the ReleaseFast app binary        (native build)
#   2. Build the MCP sidecar binary            (zig build in mcp/)
#   3. Vendor a relocatable llama-server tree  (packaging/vendor-llama.sh)
#   4. Assemble the .app bundle                (native package, ad-hoc signed)
#   5. Vendor the sidecars into the bundle + install a launcher that wires
#      BLOCKS_MCP_SERVER / BLOCKS_LLAMA_SERVER to the bundled binaries so the
#      app finds them regardless of where the user drags the .app.
#   6. Re-sign the whole bundle ad-hoc and zip it.
#
# The app spawns two child processes at runtime (the MCP memory server and the
# llama.cpp chat runtime). Neither is on a fresh Mac's PATH, and the SDK has no
# self-exe-path effect, so the launcher exports absolute paths into the child
# environment (children inherit it). See docs/PROGRESS.md "Packaging".
#
# Usage: packaging/package-macos.sh [--skip-llama]
#   --skip-llama  Skip vendoring llama-server (produces a smaller bundle that
#                 relies on $BLOCKS_LLAMA_SERVER / PATH for the chat runtime).
set -euo pipefail
setopt sh_word_split 2>/dev/null || true

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

SKIP_LLAMA=0
[[ "${1:-}" == "--skip-llama" ]] && SKIP_LLAMA=1

APP_NAME="blocks"                       # manifest name = CFBundleExecutable
DISPLAY="Blocks for Developers"
DIST_DIR="$REPO_ROOT/dist"
APP_BUNDLE="$DIST_DIR/$DISPLAY.app"
ZIG="$HOME/.native/toolchains/zig-0.16.0/zig"

echo "==> [1/6] Building the app (ReleaseFast)"
native build --yes >/dev/null
APP_BIN="$REPO_ROOT/zig-out/bin/$APP_NAME"
[[ -x "$APP_BIN" ]] || { echo "error: $APP_BIN missing after native build" >&2; exit 1; }

echo "==> [2/6] Building the MCP sidecar"
( cd "$REPO_ROOT/mcp" && "$ZIG" build >/dev/null )
MCP_BIN="$REPO_ROOT/mcp/zig-out/bin/blocks-mcp"
[[ -x "$MCP_BIN" ]] || { echo "error: $MCP_BIN missing after zig build" >&2; exit 1; }

if [[ "$SKIP_LLAMA" -eq 0 ]]; then
  echo "==> [3/6] Vendoring llama-server"
  "$REPO_ROOT/packaging/vendor-llama.sh" >/dev/null
else
  echo "==> [3/6] Skipping llama-server vendoring (--skip-llama)"
fi

echo "==> [4/6] Assembling the .app bundle (native package, ad-hoc signed)"
rm -rf "$DIST_DIR"
mkdir -p "$DIST_DIR"
native package \
  --target macos \
  --output "$APP_BUNDLE" \
  --binary "$APP_BIN" \
  --assets "$REPO_ROOT/assets" \
  --signing adhoc >/dev/null

CONTENTS="$APP_BUNDLE/Contents"
MACOS_DIR="$CONTENTS/MacOS"
RES_DIR="$CONTENTS/Resources"

echo "==> [5/6] Installing sidecars + launcher"
# Move the real app binary aside; the launcher takes its CFBundleExecutable slot.
mv "$MACOS_DIR/$APP_NAME" "$MACOS_DIR/$APP_NAME-bin"

# Vendored support binaries live under Resources/vendor.
mkdir -p "$RES_DIR/vendor/mcp/bin"
cp -f "$MCP_BIN" "$RES_DIR/vendor/mcp/bin/blocks-mcp"
chmod +x "$RES_DIR/vendor/mcp/bin/blocks-mcp"

if [[ "$SKIP_LLAMA" -eq 0 ]]; then
  cp -R "$REPO_ROOT/vendor/llama" "$RES_DIR/vendor/llama"
  chmod +x "$RES_DIR/vendor/llama/bin/llama-server"
fi

# The launcher: resolve the bundle dir from $0, point the app at the bundled
# sidecars, then exec the real binary. exec keeps the same PID so macOS still
# tracks the app (and the tray/login item work). We do NOT override
# BLOCKS_LLAMA_SERVER if the user already set one (dev override wins).
cat > "$MACOS_DIR/$APP_NAME" <<'LAUNCHER'
#!/bin/zsh
# Blocks for Developers launcher — wires the bundled sidecars into the app's
# environment so the spawned MCP server and llama.cpp runtime resolve without
# a PATH/dev-override dependency. Generated by packaging/package-macos.sh.
HERE="${0:A:h}"                       # .../Contents/MacOS
RES="$HERE/../Resources"
export BLOCKS_MCP_SERVER="$RES/vendor/mcp/bin/blocks-mcp"
if [[ -x "$RES/vendor/llama/bin/llama-server" && -z "${BLOCKS_LLAMA_SERVER:-}" ]]; then
  export BLOCKS_LLAMA_SERVER="$RES/vendor/llama/bin/llama-server"
fi
exec "$HERE/blocks-bin" "$@"
LAUNCHER
chmod +x "$MACOS_DIR/$APP_NAME"

echo "==> [6/6] Re-signing the bundle (ad-hoc) + zipping"
# Sign inner Mach-Os first (deepest last is what codesign wants: --deep on the
# app re-signs everything, which is fine for ad-hoc distribution).
codesign --force --deep --sign - "$APP_BUNDLE" >/dev/null 2>&1 || \
  codesign --force --deep --sign - "$APP_BUNDLE"

ZIP_PATH="$DIST_DIR/$DISPLAY.zip"
( cd "$DIST_DIR" && /usr/bin/ditto -c -k --sequesterRsrc --keepParent "$DISPLAY.app" "$DISPLAY.zip" )

echo
echo "==> Done."
echo "    App:  $APP_BUNDLE"
echo "    Zip:  $ZIP_PATH"
du -sh "$APP_BUNDLE" "$ZIP_PATH" 2>/dev/null | sed 's/^/    /'
